version: '3'
services:
  blood-pressure-app:
    build:
      context: .
    image: blood-pressure-app:$VERSION
    container_name: blood-pressure-app
    ports:
      - "${DOCKER_PORT}:8050"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped