# creates postgres sql database image and pgadmin4 image
# login db: postgres:postgres hostname: postgres
########################################################
version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
# if you need to connect from outside, comment this in:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: measurement
    volumes:
      - /Users/clinne/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped 
volumes:
  postgres-data: